### ISSUE TITLE
Add rows and columns in simple spreadsheet template

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-LW-LD/ldrpyutils#1]
Rows in Registerinfo sheet
* source
* maintainer

Columns in register item content sheet
* source - to allow for mixed source content
* broader - one only
* inCollection?

**Comment by jyucsiro** [comment]
We can use the following:
* source --> dcterms:source
* broader --> skos:broader

@dr-shorthair - What would rdf predicate would maintainer map to?

**Comment by dr-shorthair** [comment]
maintainer – I guess one of

dcat:contactPoint – but this is a vCard ☹
foaf:maker
dct:contributor

**Comment by jyucsiro** [comment]
I would say contributor would mean something different to maintainer? There doesn't seem to be an appropriate property for a role maintainer of some resource - see http://lov.okfn.org/dataset/lov/terms?q=maintainer

**Comment by dr-shorthair** [comment]
Yes, I know. I checked there too and only found the DOAP one, which is a bit specific. 
Maintainer is a role, needs to come from a register for roles, such as http://registry.it.csiro.au/def/isotc211/CI_RoleCode or http://memory.loc.gov/diglib/loc.terms/relators/dc-contributor.html 

This one is probably best http://registry.it.csiro.au/def/isotc211/CI_RoleCode/custodian but it isn't modelled as a property.

**Comment by jyucsiro** [comment]
Updated register item content sheet in the simple template 
* comments as users hover over column header
* added scope and broader

https://github.com/CSIRO-LW-LD/ldrpyutils/raw/master/test-data/simple.xlsx

Code also now handles added columns.

Code also populates description into skos:definition and rdfs:description, and label into skos:prefLabel and rdfs:label.

See an example register item uploaded here:
http://registry.it.csiro.au/sandbox/csiro/utils/testreg1/2

Updated windows client here: https://confluence.csiro.au/display/VOCAB/Linked+Data+Registry+tools (see Excel2ldrGui > Download > Windows 64-bit client)

**Comment by dr-shorthair** [comment]
1. Inspected http://registry.it.csiro.au/sandbox/csiro/utils/testreg1/2 - looks good
2. tested windows client: unable to load data into a new register
Error message

C:\Users\cox075\AppData\Local\Temp\_MEI212122\ldrpyutils\data\prefixes.ttl does not look like a valid URI, trying to serialize this will break.
Traceback (most recent call last):
  File "Excel2ldrGui.py", line 168, in OnSend
  File "Excel2ldrGui.py", line 221, in run
  File "site-packages\ldrpyutils-0.2.4-py3.6.egg\ldrpyutils\core.py", line 48, in load_simple_file
  File "site-packages\ldrpyutils-0.2.4-py3.6.egg\ldrpyutils\core.py", line 218, in build_graph_and_post
KeyError: 'testreg4'

Excel file attached. 

[simple-1.xlsx](https://github.com/CSIRO-LW-LD/ldrpyutils/files/1577754/simple-1.xlsx)

**Comment by dr-shorthair** [comment]
Ah - found the problem - the sheet with the data needed to be renamed. 
All good now http://registry.it.csiro.au/sandbox/csiro/utils/testreg4 
I've tweaked the comments in the test spreadsheet.
