### ISSUE TITLE
Excel2LDR Excel Template does not allow multiple altLabel

### ISSUE THREAD

**Issue by SLDarnell** [CSIRO-LW-LD/ldrpyutils#19]
Current template does not allow for the assignment of multiple altLabels as there is no delimiter function for multiple terms within the cell,  limiting each concept to a single altLabel as the template currently stands.

**Comment by jyucsiro** [comment]
Propose carriage returns in a excel cell as a delimiter.
How to do this in excel: https://superuser.com/questions/73838/how-to-write-multi-lines-in-one-excel-cell

alt label is still one cell but multiple entries for a concept separated by a new line in the cell. excel2ldr tool should parse and represent as separate properties.

**Comment by jyucsiro** [comment]
This feature is implemented for altLabel now. Created a new distribution for Windows (bumped to v1.1.3). See downloads under Windows on the wiki page: https://confluence.csiro.au/display/VOCAB/Linked+Data+Registry+tools#LinkedDataRegistrytools-Excel2ldrGui 

Test run using the test-data/single.xlsx submitted to the LDR. See http://registry.it.csiro.au/sandbox/csiro/utils/testreg4/7 for the result, which shows the altLabel.

The test data is updated here: https://github.com/CSIRO-enviro-informatics/ldrpyutils/blob/master/test-data/simple.xlsx
